version: '2'

services:
  exchange_rates:
    image: localhost/exchangerate:20220914
    container_name: exchange_rates
    restart: always
    ports:
      - "8081:8888"
    environment:
      - "JAVA_OPTIONS="
    logging:
      options:
        max-size: "1G"
        max-file: "10"