version: '2'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.1.1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - "node.name=127.0.0.1"
      - "cluster.name=elastic_cluster"
      - "cluster.initial_master_nodes=127.0.0.1"
      - "discovery.seed_hosts=127.0.0.1"
      - "xpack.security.enabled=false"
      - "ES_JAVA_OPTS=-Xmx256m -Xms256m"
      - "node.store.allow_mmap=false"
    networks:
      - elk

networks:
  elk:
    driver: bridge

volumes:
  esdata:
    driver: local