version: '2'

services:
  logstash:
    image: docker.elastic.co/logstash/logstash:8.1.1
    volumes:
      # - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "5000:5000"
    environment:
      - "LS_JAVA_OPTS: -Xmx256m -Xms256m"
      - "XPACK_MONITORING_ELASTICSEARCH_HOSTS=http://elasticsearch:9200"
      - "XPACK_MONITORING_ENABLED=true"
    networks:
      - elk
    depends_on:
      - elasticsearch
    links:
      - elasticsearch

networks:
  elk:
    driver: bridge
